language: java
sudo: false
stages:
  - Build
  - Perform Release
  - Push Docker
    if: branch = master
jobs:
  include:
    - stage: Build
      name: Gradle Build
      script: ./gradlew clean build
    - stage: Perform Release
      name: Shipkit Perform Release
      script: ./gradlew ciPerformRelease
    - stage: Push Docker
      name: jib
      script: ./gradlew jib -x test
script: ./gradlew clean build -s && ./gradlew ciPerformRelease
matrix:
  include:
    - jdk: openjdk11
#don't build tags
branches:
  except:
    - /^v\d/
dist: trusty
env:
  global:
    - java.io.tmpdir=/tmp
