language: java
os: linux
services:
  - docker
stages:
  - "Build"
  - name: "E2E"
    if: branch = master or type = pull_request
  - name: "Perform Release"
    if: branch = master and type != pull_request
jobs:
  include:
    - stage: "Build"
      name: "Gradle Build"
      script: ./gradlew clean build
    - stage: "E2E"
      name: "Check Capybara Compiled Files"
      before_install:
        - docker pull mgrzeslowski/capybara:0.1.4
        - docker build src/test/resources -t integration_test
      script: docker run integration_test
    - stage: "Perform Release"
      name: "Release to Bintray"
      script: ./gradlew ciPerformRelease
    - stage: "Perform Release"
      name: "Push Docker"
      script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && ./gradlew jib -x test
jdk: openjdk11
#don't build tags
branches:
  except:
    - /^v\d/
dist: trusty
env:
  global:
    - java.io.tmpdir=/tmp
