language: java
os: linux
stages:
  - "Build"
  - name: "Perform Release"
    if: branch = master and type != pull_request
  - name: "Push Docker"
    if: branch = master and type != pull_request
jobs:
  include:
    - stage: "Build"
      name: "Gradle Build"
      script: ./gradlew clean build
    - stage: "Perform Release"
      name: "Shipkit Perform Release"
      script: ./gradlew ciPerformRelease
    - stage: "Push Docker"
      name: "jib"
      script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && ./gradlew jib -x test
jdk: openjdk11
#don't build tags
branches:
  except:
    - /^v\d/
dist: trusty
env:
  global:
    - java.io.tmpdir=/tmp
