language: java
sudo: false
#script: ./gradlew clean build -s && ./gradlew ciPerformRelease
script: ./gradlew clean build --debug --stacktrace
matrix:
  include:
    - jdk: openjdk11
#don't build tags
branches:
  except:
    - /^v\d/
dist: trusty
env:
  global:
    - java.io.tmpdir=/tmp
