= Module SemVer

== Functions

=== fun parse_semver(version: xref:../../capy/lang/String.adoc#type-String[String]): xref:../../capy/lang/Result.adoc#type-Result[Result]&#91;xref:#type-SemVer[SemVer]&#93;

https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions[Backus–Naur Form Grammar for Valid SemVer Versions]

```
<valid semver> ::= <version core>
                 | <version core> "-" <pre-release>
                 | <version core> "+" <build>
                 | <version core> "-" <pre-release> "+" <build>
```


=== fun sem_ver(major_value: int, minor_value: int, patch_value: int, pre_release: xref:../../capy/lang/Option.adoc#type-Option[Option]&#91;xref:../../capy/lang/String.adoc#type-String[String]&#93;, build_metadata: xref:../../capy/lang/Option.adoc#type-Option[Option]&#91;xref:../../capy/lang/String.adoc#type-String[String]&#93;): xref:../../capy/lang/Result.adoc#type-Result[Result]&#91;xref:#type-SemVer[SemVer]&#93;

Creates a semantic version after validating the numeric components.




== Types

[[type-SemVer]]
=== data SemVer

Given a version number MAJOR.MINOR.PATCH, increment the:

1. MAJOR version when you make incompatible API changes
2. MINOR version when you add functionality in a backward compatible manner
3. PATCH version when you make backward compatible bug fixes

Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
Full specification: https://semver.org/

Example:
```cfun
let version <- sem_ver(1, 2, 3, None {}, Some { "build.7" })
version.to_string() == "1.2.3+build.7"
```

==== Fields

* `build_metadata`: xref:../../capy/lang/Option.adoc#type-Option[Option]&#91;xref:../../capy/lang/String.adoc#type-String[String]&#93;
* `major`: xref:#type-major[major]
* `minor`: xref:#type-minor[minor]
* `patch`: xref:#type-patch[patch]
* `pre_release`: xref:../../capy/lang/Option.adoc#type-Option[Option]&#91;xref:../../capy/lang/String.adoc#type-String[String]&#93;

==== Functions

===== fun SemVer.`<=`(other: xref:#type-SemVer[SemVer]): bool

Returns true when this SemVer version has the same or lower precedence than `other`.


===== fun SemVer.`<`(other: xref:#type-SemVer[SemVer]): bool

Returns true when this SemVer version has lower precedence than `other`.


===== fun SemVer.`==`(other: xref:#type-SemVer[SemVer]): bool

Returns true when this SemVer version has the same precedence as `other`.


===== fun SemVer.`>=`(other: xref:#type-SemVer[SemVer]): bool

Returns true when this SemVer version has the same or higher precedence than `other`.


===== fun SemVer.`>`(other: xref:#type-SemVer[SemVer]): bool

Returns true when this SemVer version has higher precedence than `other`.


===== fun SemVer.compare(other: xref:#type-SemVer[SemVer]): xref:../../capy/lang/Ordering.adoc#type-Ordering[Ordering]

Compares this SemVer version with `other` using Semantic Versioning precedence.

Build metadata does not affect precedence.


===== fun SemVer.to_string(): xref:../../capy/lang/String.adoc#type-String[String]

Generates a string representation of this SemVer version, e.g. `1.0.0`, `2.1.3-alpha`, `3.2.1+build.123`, `4.5.6-beta+exp.sha.5114f85`


[[type-major]]
=== type major: int

Semantic version major component, greater than or equal to zero.

==== Functions

===== fun major.`<=`(other: xref:#type-major[major]): bool

Returns whether this major component is less than or equal to `other`.


===== fun major.`<`(other: xref:#type-major[major]): bool

Returns whether this major component is less than `other`.


===== fun major.`==`(other: xref:#type-major[major]): bool

Returns whether this major component has the same value as `other`.


===== fun major.`>=`(other: xref:#type-major[major]): bool

Returns whether this major component is greater than or equal to `other`.


===== fun major.`>`(other: xref:#type-major[major]): bool

Returns whether this major component is greater than `other`.



[[type-minor]]
=== type minor: int

Semantic version minor component, greater than or equal to zero.

==== Functions

===== fun minor.`<=`(other: xref:#type-minor[minor]): bool

Returns whether this minor component is less than or equal to `other`.


===== fun minor.`<`(other: xref:#type-minor[minor]): bool

Returns whether this minor component is less than `other`.


===== fun minor.`==`(other: xref:#type-minor[minor]): bool

Returns whether this minor component has the same value as `other`.


===== fun minor.`>=`(other: xref:#type-minor[minor]): bool

Returns whether this minor component is greater than or equal to `other`.


===== fun minor.`>`(other: xref:#type-minor[minor]): bool

Returns whether this minor component is greater than `other`.



[[type-patch]]
=== type patch: int

Semantic version patch component, greater than or equal to zero.

==== Functions

===== fun patch.`<=`(other: xref:#type-patch[patch]): bool

Returns whether this patch component is less than or equal to `other`.


===== fun patch.`<`(other: xref:#type-patch[patch]): bool

Returns whether this patch component is less than `other`.


===== fun patch.`==`(other: xref:#type-patch[patch]): bool

Returns whether this patch component has the same value as `other`.


===== fun patch.`>=`(other: xref:#type-patch[patch]): bool

Returns whether this patch component is greater than or equal to `other`.


===== fun patch.`>`(other: xref:#type-patch[patch]): bool

Returns whether this patch component is greater than `other`.



