= Module Interval

== Functions

=== fun from_iso_8601(iso: xref:../../capy/lang/String.adoc#type-String[String]): xref:../../capy/lang/Result.adoc#type-Result[Result]&#91;xref:#type-Interval[Interval]&#93;

Parses an ISO 8601 interval in one of these forms:
- `<start>/<end>`
- `<start>/<duration>`
- `<duration>/<end>`

Also accepts `--` as an alternate input separator and canonicalizes back to `/`.

Example:
```cfun
from_iso_8601("1970-01-01T00:00:00Z/P1D")
from_iso_8601("P1D/1970-01-02T00:00:00Z")
```
Both describe a one-day interval.




== Types

[[type-DateTimeDurationEnd]]
=== data DateTimeDurationEnd

Interval stored with a duration and end date-time.

==== Fields

* `duration`: xref:../../capy/date_time/Duration.adoc#type-Duration[Duration]
* `end`: xref:../../capy/date_time/DateTime.adoc#type-DateTime[DateTime]

[[type-DateTimeStartDuration]]
=== data DateTimeStartDuration

Interval stored with a start date-time and duration.

==== Fields

* `duration`: xref:../../capy/date_time/Duration.adoc#type-Duration[Duration]
* `start`: xref:../../capy/date_time/DateTime.adoc#type-DateTime[DateTime]

[[type-DateTimeStartEnd]]
=== data DateTimeStartEnd

Interval stored with explicit start and end date-times.

==== Fields

* `end`: xref:../../capy/date_time/DateTime.adoc#type-DateTime[DateTime]
* `start`: xref:../../capy/date_time/DateTime.adoc#type-DateTime[DateTime]

[[type-Interval]]
=== union Interval

ISO 8601 interval represented using UTC date-time endpoints.

An interval can be stored as start/end, start/duration, or duration/end.

Example:
```cfun
DateTimeStartDuration {
    start: UNIX_EPOCH,
    duration: DateDuration {
        years: 0, months: 0, days: 1,
        hours: 0, minutes: 0, seconds: 0
    }
}
```

==== Variants

* xref:#type-DateTimeDurationEnd[DateTimeDurationEnd]
* xref:#type-DateTimeStartDuration[DateTimeStartDuration]
* xref:#type-DateTimeStartEnd[DateTimeStartEnd]

==== Functions

===== fun Interval.duration(): xref:../../capy/date_time/Duration.adoc#type-Duration[Duration]

Returns the interval duration.


===== fun Interval.end(): xref:../../capy/date_time/DateTime.adoc#type-DateTime[DateTime]

Returns the interval end date-time.

For `DateTimeStartDuration`, the end is calculated by adding the duration to
the start.


===== fun Interval.start(): xref:../../capy/date_time/DateTime.adoc#type-DateTime[DateTime]

Returns the interval start date-time.

For `DateTimeDurationEnd`, the start is calculated by subtracting the
duration from the end.


===== fun Interval.to_iso_8601(): xref:../../capy/lang/String.adoc#type-String[String]

Formats this interval as canonical ISO 8601 using `/` as the separator.

Example:
```cfun
DateTimeStartEnd {
    start: UNIX_EPOCH,
    end: from_timestamp(3600L)
}.to_iso_8601()
```
Returns `1970-01-01T00:00:00Z/1970-01-01T01:00:00Z`.


