/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import org.apache.commons.text.WordUtils;

import static org.example.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        var normalized = getMessage().trim().replaceAll("\\s+", " ");
        System.out.println(WordUtils.capitalize(normalized));
    }
}
