package dev.capylang.generator;

import dev.capylang.compiler.CapybaraCompiler;
import dev.capylang.compiler.CompiledProgram;
import dev.capylang.compiler.NativeProviderBackendBinding;
import dev.capylang.compiler.NativeProviderBinding;
import dev.capylang.compiler.NativeProviderManifest;
import dev.capylang.compiler.Result;
import dev.capylang.compiler.generator.PythonGenerationPass;
import dev.capylang.compiler.parser.RawModule;
import dev.capylang.compiler.parser.SourceKind;
import org.junit.jupiter.api.Test;

import java.nio.file.Path;
import java.util.List;
import java.util.TreeSet;

import static java.util.stream.Collectors.joining;
import static org.assertj.core.api.Assertions.assertThat;

class PythonGenerationPassTest {
    @Test
    void shouldPlanPythonFilesAndRenderNativeProviderBootstrapInCapybara() {
        List<List<?>> rendered = List.of(PythonGenerationPass.generatedPythonFile("foo/Main.py", "def answer():\n    return 42\n"));
        List<List<?>> providers = List.of(PythonGenerationPass.pythonNativeProviderInfo(
                "system_clock",
                "system_clock",
                "/Providers.Clock",
                "system",
                "/ProvidersNative.cfun",
                "host_clock",
                "SystemClock",
                "call",
                List.of(PythonGenerationPass.pythonNativeProviderMethodInfo("now_millis", 0))
        ));

        var plan = PythonGenerationPass.planPythonGeneration(rendered, providers);

        assertThat(plan)
                .extracting(PythonGenerationPassTest::generatedFilePath)
                .containsExactly("foo/Main.py", "dev/capylang/native_providers.py");
        assertThat(generatedFileCode(plan.getLast())).isEqualTo("""
                # Generated by Capybara. Do not edit.
                import dev.capylang.capybara as capy
                __capy_provider_system_clock_class = capy.require_native_provider_class(module_name='host_clock', class_name='SystemClock', metadata={'interfaceId': '/Providers.Clock', 'qualifier': 'system', 'providerSymbol': 'system_clock', 'backend': 'python', 'sourceFile': '/ProvidersNative.cfun', 'moduleName': 'host_clock', 'className': 'SystemClock'})

                _providers = capy.define_native_providers({
                    '/Providers.Clock#system': capy.native_factory(
                        interface_id='/Providers.Clock',
                        qualifier='system',
                        provider_symbol='system_clock',
                        backend='python',
                        source_file='/ProvidersNative.cfun',
                        module_name='host_clock',
                        class_name='SystemClock',
                        factory='call',
                        metadata={'methods': [{'name': 'now_millis', 'arity': 0}]},
                        create=lambda: __capy_provider_system_clock_class(),
                    ),
                })

                def system_clock():
                    return _providers.resolve('/Providers.Clock', 'system', 'system_clock', 'python', '/ProvidersNative.cfun')

                """);
    }

    @Test
    void shouldMatchLegacyPythonGeneratorOutputInTransitionParityMode() {
        var program = compileProgram(List.of(
                new RawModule(
                        "Providers",
                        "",
                        """
                                interface Clock {
                                    def now_millis(): long
                                }
                                """,
                        SourceKind.OBJECT_ORIENTED
                ),
                new RawModule("ProvidersNative", "", """
                        from /capy/lang/Effect import { Effect }
                        from /capy/meta_prog/NativeProvider import { NativeProvider }
                        from Providers import { Clock }

                        @NativeProvider(qualifier: "system")
                        fun system_clock(): Effect[Clock] = <native>
                        """),
                new RawModule(
                        "ClockConsumer",
                        "",
                        """
                                from Providers import { Clock }
                                from ProvidersNative import { system_clock }

                                class ClockConsumer {
                                    def current(): Clock = system_clock()
                                }
                                """,
                        SourceKind.OBJECT_ORIENTED
                )
        ), new NativeProviderManifest(List.of(new NativeProviderBinding(
                "/Providers.Clock",
                "system",
                null,
                null,
                new NativeProviderBackendBinding("SystemClock", "nativeinterop.system_clock", null, "call")
        ))));

        var capybaraPlannedOutput = new PythonGenerator().generate(program);
        var legacyOutput = PythonGenerator.legacyParityMode().generate(program);

        assertThat(normalize(capybaraPlannedOutput.modules())).containsExactlyElementsOf(normalize(legacyOutput.modules()));
        assertThat(capybaraPlannedOutput.modules())
                .extracting(GeneratedModule::relativePath)
                .contains(Path.of("dev", "capylang", "native_providers.py"));
    }

    private static CompiledProgram compileProgram(List<RawModule> modules, NativeProviderManifest nativeProviders) {
        var allModules = new java.util.ArrayList<RawModule>();
        allModules.add(new RawModule("NativeProvider", "/capy/meta_prog", """
                annotation NativeProvider on fun {
                    qualifier: String = ""
                }
                """));
        allModules.addAll(modules);
        var result = CapybaraCompiler.INSTANCE.compile(allModules, new TreeSet<>(), nativeProviders);
        if (result instanceof Result.Error<CompiledProgram> error) {
            throw new AssertionError(error.errors().stream()
                    .map(Result.Error.SingleError::message)
                    .collect(joining(", ")));
        }
        return ((Result.Success<CompiledProgram>) result).value();
    }

    private static List<GeneratedModule> normalize(List<GeneratedModule> modules) {
        return modules.stream()
                .map(module -> new GeneratedModule(module.relativePath(), module.code().replace("\r\n", "\n")))
                .toList();
    }

    private static String generatedFilePath(List<?> file) {
        return PythonGenerationPass.generatedPythonFileRelativePath(file);
    }

    private static String generatedFileCode(List<?> file) {
        return PythonGenerationPass.generatedPythonFileCode(file);
    }
}
