= Module Program

== Constants

=== public DEFAULT_FAILED_EXIT_CODE: 

Default failure exit code for generic program errors.


=== public LAST_FAILED_EXIT_CODE: 

Last valid failure exit code.


=== public SIGABRT: 

Abort signal exit code.


=== public SIGALRM: 

Alarm or timeout signal exit code.


=== public SIGFPE: 

Floating point exception signal exit code.


=== public SIGHUP: 

Hangup signal exit code.


=== public SIGINT: 

Interrupt signal exit code.


=== public SIGKILL: 

Forced kill signal exit code.


=== public SIGPIPE: 

Broken pipe signal exit code.


=== public SIGQUIT: 

Quit signal exit code.


=== public SIGSEGV: 

Segmentation fault signal exit code.


=== public SIGTERM: 

Termination signal exit code.




== Types

[[type-Failed]]
=== data Failed

Failed program completion with a non-zero exit code.

==== Fields

* `exit_code`: xref:#type-failed_exit_code[failed_exit_code]

[[type-Program]]
=== union Program

Process result returned by an executable Capybara `main` function.

==== Variants

* xref:#type-Failed[Failed]
* xref:#type-Success[Success]

[[type-Success]]
=== data Success

Successful program completion with exit code `0`.

[[type-failed_exit_code]]
=== public failed_exit_code: int

Valid process failure exit code in the portable range `1..255`.

==== Functions

===== public failed_exit_code.next(): xref:#type-failed_exit_code[failed_exit_code]

Returns the next failure exit code, clamped to `LAST_FAILED_EXIT_CODE`.


===== public failed_exit_code.previous(): xref:#type-failed_exit_code[failed_exit_code]

Returns the previous failure exit code, clamped to `DEFAULT_FAILED_EXIT_CODE`.



