= Module Program

== Constants

=== const DEFAULT_FAILED_EXIT_CODE: 

Default failure exit code for generic program errors.


=== const LAST_FAILED_EXIT_CODE: 

Last valid failure exit code.


=== const SIGABRT: 

Abort signal exit code.


=== const SIGALRM: 

Alarm or timeout signal exit code.


=== const SIGFPE: 

Floating point exception signal exit code.


=== const SIGHUP: 

Hangup signal exit code.


=== const SIGINT: 

Interrupt signal exit code.


=== const SIGKILL: 

Forced kill signal exit code.


=== const SIGPIPE: 

Broken pipe signal exit code.


=== const SIGQUIT: 

Quit signal exit code.


=== const SIGSEGV: 

Segmentation fault signal exit code.


=== const SIGTERM: 

Termination signal exit code.




== Types

[[type-Failed]]
=== data Failed

Failed program completion with a non-zero exit code.

==== Fields

* `exit_code`: xref:#type-failed_exit_code[failed_exit_code]

[[type-Program]]
=== union Program

Process result returned by an executable Capybara `main` function.

==== Variants

* xref:#type-Failed[Failed]
* xref:#type-Success[Success]

[[type-Success]]
=== data Success

Successful program completion with exit code `0`.

[[type-failed_exit_code]]
=== type failed_exit_code: int

Valid process failure exit code in the portable range `1..255`.

==== Functions

===== fun failed_exit_code.next(): xref:#type-failed_exit_code[failed_exit_code]

Returns the next failure exit code, clamped to `LAST_FAILED_EXIT_CODE`.


===== fun failed_exit_code.previous(): xref:#type-failed_exit_code[failed_exit_code]

Returns the previous failure exit code, clamped to `DEFAULT_FAILED_EXIT_CODE`.



