<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>Capybara</string>
  <key>scopeName</key>
  <string>source.capybara</string>
  <key>fileTypes</key>
  <array>
    <string>cfun</string>
    <string>coo</string>
  </array>
  <key>patterns</key>
  <array>
    <dict><key>name</key><string>markup.quote.todo.comment.line.capybara</string><key>match</key><string>//[/]?\s*(?i:todo)\b.*$</string></dict>
    <dict><key>name</key><string>markup.changed.fixme.comment.line.capybara</string><key>match</key><string>//[/]?\s*(?i:fixme)\b.*$</string></dict>
    <dict><key>name</key><string>comment.block.capybara</string><key>begin</key><string>/\*</string><key>end</key><string>\*/</string></dict>
    <dict><key>name</key><string>comment.block.documentation.capybara</string><key>match</key><string>///.*$</string></dict>
    <dict><key>name</key><string>comment.line.double-slash.capybara</string><key>match</key><string>//.*$</string></dict>
    <dict>
      <key>name</key><string>string.quoted.double.capybara</string>
      <key>begin</key><string>"</string>
      <key>end</key><string>"</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key><string>meta.interpolation.capybara</string>
          <key>contentName</key><string>meta.embedded.expression.capybara</string>
          <key>begin</key><string>(?&lt;!\\)\{(?=(?:[^"\\]|\\.)*(?&lt;!\\)\})</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key><dict><key>name</key><string>punctuation.section.embedded.begin.capybara</string></dict>
          </dict>
          <key>end</key><string>(?&lt;!\\)\}</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key><dict><key>name</key><string>punctuation.section.embedded.end.capybara</string></dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict><key>include</key><string>#comments</string></dict>
            <dict><key>include</key><string>#strings</string></dict>
            <dict><key>include</key><string>#numbers</string></dict>
            <dict><key>include</key><string>#keywords</string></dict>
            <dict><key>include</key><string>#typesAndFunctions</string></dict>
            <dict><key>include</key><string>#operatorsAndBrackets</string></dict>
            <dict><key>name</key><string>constant.character.escape.capybara</string><key>match</key><string>\\.</string></dict>
          </array>
        </dict>
        <dict><key>name</key><string>constant.character.escape.capybara</string><key>match</key><string>\\.</string></dict>
      </array>
    </dict>
    <dict>
      <key>name</key><string>string.quoted.single.capybara</string>
      <key>begin</key><string>'</string>
      <key>end</key><string>'</string>
      <key>patterns</key>
      <array>
        <dict><key>name</key><string>constant.character.escape.capybara</string><key>match</key><string>\\.</string></dict>
      </array>
    </dict>
    <dict><key>name</key><string>keyword.control.capybara</string><key>match</key><string>\b(fun|def|type|enum|data|single|const|local|match|with|constructor|case|when|if|then|else|let|return|throw|try|catch|this|from|import|except|class|trait|interface|field|open|abstract|override|final|private|public|init|super|while|do|for|foreach|in)\b</string></dict>
    <dict><key>name</key><string>keyword.operator.constructor.capybara</string><key>match</key><string>(?&lt;=\bconstructor\s*\{[^\n]*)\*(?=\s*\{)</string></dict>
    <dict><key>name</key><string>keyword.other.capybara</string><key>match</key><string>\\b(is_empty|size|to_int|to_long|to_double|to_float|to_bool)\\b</string></dict>
    <dict><key>name</key><string>support.type.primitive.capybara</string><key>match</key><string>\b(byte|int|long|float|double|bool|string|any|data|void|list|set|dict|tuple)(?:\[\])*(?=\b|[^A-Za-z0-9_])</string></dict>
    <dict><key>name</key><string>constant.numeric.capybara</string><key>match</key><string>\b(?:0[xX][0-9a-fA-F]+|\d+[lL]|\d+\.\d*(?:[eE][+\-]?\d+)?[fFdD]?|\d+[eE][+\-]?\d+[fFdD]?|\d+)\b</string></dict>
    <dict><key>name</key><string>constant.language.boolean.capybara</string><key>match</key><string>\b(true|false)\b</string></dict>
    <dict><key>name</key><string>constant.language.unimplemented.capybara</string><key>match</key><string>\?\?\?</string></dict>
    <dict><key>name</key><string>constant.language.native.capybara</string><key>match</key><string>&lt;native&gt;</string></dict>
    <dict><key>name</key><string>punctuation.separator.local-definitions.capybara</string><key>match</key><string>---</string></dict>
    <dict>
      <key>name</key><string>meta.function.documented.private.capybara</string>
      <key>match</key><string>((?:^\s*///.*\r?\n)+)(\s*)((?:fun|def))(\s+)(__[A-Za-z0-9_]+)</string>
      <key>captures</key>
      <dict>
        <key>1</key><dict><key>name</key><string>comment.block.documentation.capybara</string></dict>
        <key>3</key><dict><key>name</key><string>keyword.control.capybara</string></dict>
        <key>5</key><dict><key>name</key><string>entity.name.function.private.capybara</string></dict>
      </dict>
    </dict>
    <dict>
      <key>name</key><string>meta.function.documented.capybara</string>
      <key>match</key><string>((?:^\s*///.*\r?\n)+)(\s*)((?:fun|def))(\s+)([A-Za-z_][A-Za-z0-9_]*)</string>
      <key>captures</key>
      <dict>
        <key>1</key><dict><key>name</key><string>comment.block.documentation.capybara</string></dict>
        <key>3</key><dict><key>name</key><string>keyword.control.capybara</string></dict>
        <key>5</key><dict><key>name</key><string>entity.name.function.capybara</string></dict>
      </dict>
    </dict>
    <dict><key>name</key><string>meta.type.constructor.capybara</string><key>match</key><string>\b(type)\s+(_*[A-Z][A-Za-z0-9_]*(?:\[[^\]]+\])?)(?:\s*\{[^{}\n]*\})?\s+(with)\s+(constructor)\s*\{</string></dict>
    <dict>
      <key>name</key><string>meta.data.constructor-bypass.capybara</string>
      <key>match</key><string>(_*[A-Z][A-Za-z0-9_]*(?:\[[^\]]+\])?)(!)(?=\s*\{)</string>
      <key>captures</key>
      <dict>
        <key>1</key><dict><key>name</key><string>entity.name.type.capybara</string></dict>
        <key>2</key><dict><key>name</key><string>keyword.operator.constructor.capybara</string></dict>
      </dict>
    </dict>
    <dict><key>name</key><string>entity.name.type.capybara</string><key>match</key><string>\b_*[A-Z][A-Za-z0-9_]*(?:\[\])*(?=\b|[^A-Za-z0-9_])</string></dict>
    <dict><key>name</key><string>entity.name.type.private.capybara</string><key>match</key><string>\b(type|enum|data|single|class|trait|interface)\s+(__[A-Za-z0-9_]*)</string></dict>
    <dict><key>name</key><string>entity.name.type.capybara</string><key>match</key><string>\b(class|trait|interface)\s+(_*[A-Z][A-Za-z0-9_]*)</string></dict>
    <dict><key>name</key><string>entity.name.function.private.capybara</string><key>match</key><string>\bfun\s+(__[A-Za-z0-9_]+)</string></dict>
    <dict><key>name</key><string>entity.name.function.capybara</string><key>match</key><string>\bfun\s+([A-Za-z_][A-Za-z0-9_]*)</string></dict>
    <dict><key>name</key><string>meta.function.owner-generic.capybara</string><key>match</key><string>\b(fun)\s+(_*[A-Z][A-Za-z0-9_]*\[[^\]]+\])\.(?:`[^`]+`|[A-Za-z_][A-Za-z0-9_]*)</string></dict>
    <dict><key>name</key><string>meta.function.owner-infix.capybara</string><key>match</key><string>\b(fun)\s+(_*[A-Z][A-Za-z0-9_]*)\.([^]+)</string></dict>
    <dict><key>name</key><string>entity.name.function.private.capybara</string><key>match</key><string>:(__[A-Za-z0-9_]+)\b</string></dict>
    <dict><key>name</key><string>entity.name.function.capybara</string><key>match</key><string>:([A-Za-z_][A-Za-z0-9_]*)\b</string></dict>
    <dict><key>name</key><string>entity.name.function.private.capybara</string><key>match</key><string>\b(__[A-Za-z0-9_]+)\s*(?=\()</string></dict>
    <dict><key>name</key><string>entity.name.function.capybara</string><key>match</key><string>\b([A-Za-z_][A-Za-z0-9_]*)\s*(?=\()</string></dict>
    <dict>
      <key>name</key><string>meta.let.declaration.capybara</string>
      <key>match</key><string>\b(let)\s+([A-Za-z_][A-Za-z0-9_]*)\b</string>
    </dict>
    <dict>
      <key>name</key><string>meta.const.private.capybara</string>
      <key>match</key><string>\b(const)\s+(__[A-Za-z_][A-Za-z0-9_]*)\b</string>
    </dict>
    <dict>
      <key>name</key><string>meta.const.capybara</string>
      <key>match</key><string>\b(const)\s+(_*[A-Z_][A-Z0-9_]*)\b</string>
    </dict>
    <dict>
      <key>name</key><string>meta.match.case-branch.capybara</string>
      <key>match</key><string>(\bcase\b)([^\n]*?)(-&gt;)</string>
    </dict>
    <dict>
      <key>name</key><string>meta.match.typed-pattern.capybara</string>
      <key>match</key><string>(\bcase\b)\s*(_*[A-Z][A-Za-z0-9_]*)\s+([A-Za-z_][A-Za-z0-9_]*|_)\s*(=&gt;)</string>
    </dict>
    <dict>
      <key>name</key><string>meta.match.wildcard-binding.capybara</string>
      <key>match</key><string>(\bcase\b)\s*(_)\s+([A-Za-z_][A-Za-z0-9_]*)\s*(=&gt;)</string>
    </dict>
    <dict>
      <key>name</key><string>meta.match.constructor-pattern.capybara</string>
      <key>match</key><string>(\bcase\b)\s*(_*[A-Z][A-Za-z0-9_]*)\s*(\{)\s*([A-Za-z_][A-Za-z0-9_]*)</string>
    </dict>
    <dict>
      <key>name</key><string>meta.pipe.lambda.grouped.single.capybara</string>
      <key>match</key><string>(\|all\?|\|any\?|\|>|\|\*|\|-|\|)\s*(\()\s*([A-Za-z_][A-Za-z0-9_]*|_)\s*(=&gt;)</string>
    </dict>
    <dict>
      <key>name</key><string>meta.pipe.lambda.grouped.tuple.capybara</string>
      <key>match</key><string>(\|all\?|\|any\?|\|>|\|\*|\|-|\|)\s*(\()\s*([A-Za-z_][A-Za-z0-9_]*|_)(\s*,\s*([A-Za-z_][A-Za-z0-9_]*|_))+\s*(\))\s*(=&gt;)</string>
    </dict>
    <dict>
      <key>name</key><string>meta.pipe.lambda.grouped.no-args.capybara</string>
      <key>match</key><string>(\|all\?|\|any\?|\|>|\|\*|\|-|\|)\s*(\()\s*(\))\s*(=&gt;)</string>
    </dict>
    <dict>
      <key>name</key><string>variable.parameter.unused.capybara</string>
      <key>match</key><string>(?&lt;=\(|,)\s*(_)(?=\s*(?:,|\)\s*=&gt;))</string>
    </dict>
    <dict>
      <key>name</key><string>meta.lambda.tuple-destructure.capybara</string>
      <key>match</key><string>(\()\s*([A-Za-z_][A-Za-z0-9_]*|_)(\s*,\s*([A-Za-z_][A-Za-z0-9_]*|_))+\s*(\))\s*(=&gt;)</string>
    </dict>
    <dict>
      <key>name</key><string>meta.lambda.no-args.capybara</string>
      <key>match</key><string>(\()\s*(\))\s*(=&gt;)</string>
    </dict>
    <dict>
      <key>name</key><string>meta.method.with.named-argument.capybara</string>
      <key>match</key><string>((?:\.with\(|,)\s*)([A-Za-z_][A-Za-z0-9_]*)(\s*=)</string>
    </dict>
    <dict><key>name</key><string>keyword.operator.function-type.capybara</string><key>match</key><string>=&gt;</string></dict>
    <dict><key>name</key><string>keyword.operator.pipe.capybara</string><key>match</key><string>\|all\?|\|any\?|\|>|\|\*|\|-|\||\.\.\.|\.and\.|\.nand\.|\.or\.|\.xor\.|\.not\.|==|!=|&lt;-|&lt;=|&gt;=|=&gt;|\+|\-|\*|/|%|\^|&lt;|&gt;|=|&amp;|\?|:|,</string></dict>
    <dict>
      <key>name</key><string>meta.index.capybara</string>
      <key>begin</key><string>\[</string>
      <key>end</key><string>\]</string>
      <key>patterns</key>
      <array>
        <dict><key>name</key><string>markup.quote.todo.comment.line.capybara</string><key>match</key><string>//[/]?\s*(?i:todo)\b.*$</string></dict>
        <dict><key>name</key><string>markup.changed.fixme.comment.line.capybara</string><key>match</key><string>//[/]?\s*(?i:fixme)\b.*$</string></dict>
        <dict><key>name</key><string>comment.block.capybara</string><key>begin</key><string>/\*</string><key>end</key><string>\*/</string></dict>
        <dict><key>name</key><string>comment.block.documentation.capybara</string><key>match</key><string>///.*$</string></dict>
        <dict><key>name</key><string>comment.line.double-slash.capybara</string><key>match</key><string>//.*$</string></dict>
        <dict>
          <key>name</key><string>string.quoted.double.capybara</string>
          <key>begin</key><string>"</string>
          <key>end</key><string>"</string>
          <key>patterns</key>
          <array>
            <dict><key>name</key><string>constant.character.escape.capybara</string><key>match</key><string>\\.</string></dict>
          </array>
        </dict>
        <dict>
          <key>name</key><string>string.quoted.single.capybara</string>
          <key>begin</key><string>'</string>
          <key>end</key><string>'</string>
          <key>patterns</key>
          <array>
            <dict><key>name</key><string>constant.character.escape.capybara</string><key>match</key><string>\\.</string></dict>
          </array>
        </dict>
        <dict><key>name</key><string>keyword.operator.capybara</string><key>match</key><string>:</string></dict>
        <dict><key>name</key><string>keyword.operator.pipe.capybara</string><key>match</key><string>\|all\?|\|any\?|\|>|\|\*|\|-|\||\.\.\.|\.and\.|\.nand\.|\.or\.|\.xor\.|\.not\.|==|!=|&lt;-|&lt;=|&gt;=|=&gt;|\+|\-|\*|/|%|\^|&lt;|&gt;|=|&amp;|\?|:|,</string></dict>
        <dict><key>name</key><string>constant.numeric.int.capybara</string><key>match</key><string>-?\d+</string></dict>
      </array>
    </dict>
  </array>
</dict>
</plist>
